config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
             controllers: {
                 passwords: 'user/passwords',
                 registrations: 'user/registrations',
                 sessions: 'user/sessions',
                 confirmations: 'user/confirmations',
                 unlocks: 'user/unlocks'
             },
             path: 'user',
             path_names: {
                 sign_in: 'login',
                 sign_out: 'logout',
                 password: 'password',
                 confirmation: 'confirm',
                 unlock: 'reset',
                 registration: 'register',
                 sign_up: 'signup'
             }

  root to: 'referrals#new'

  get '/static/:page' => 'static_pages#show'

  resource :users do
    resource :referrals
  end

end

app/views/shared/_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-dismissible fade in <%= bootstrap_class_for(type) %>" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <% if @event.try(:errors).try(:any?) %>
      <ul class="list-unstyled">
        <% @event.errors.full_messages.each do |message| %>
          <li><%= t(message) %></li>
        <% end %>
      </ul>
    <% else %>
      <%= t(message) %>
    <% end %>
  </div>
<% end %>

app/views/shared/_panel.html.erb
<% return unless content_for? :panel_body %>
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <% if content_for? :panel_title %>
        <div class="panel-heading">
          <h3 class="panel-title">
            <%= yield :panel_title %>
          </h3>
        </div>
      <% end %>
      <div class="panel-body">
        <% if content_for? :panel_body %>
        <%= yield :panel_body %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_topnav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Refer Me</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= active_class(new_users_referrals_path) %>" ><a href="<%= new_users_referrals_path %>"><%= t('refer_someone') %></a></li>
        <li class="<%= active_class(users_referrals_path) %>" ><a href="<%= users_referrals_path %>"><%= t('my_referrals') %></a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= t('my_profile') %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to t('edit_credentials'), edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to t('logout'), destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>